swagger: '2.0'
info:
  version: 1.0.0
  title: registry_search-v1
  description: Api to search gift registries
host: api.target.com
schemes:
  - https
basePath: /registries_search/v1
produces:
  - application/json
consumes:
  - application/json
x-api-definition:
  api_name: registries_search-v1
  personnel:
    portfolio: Digital
    owner: Indrakumar.Thimmaiah
    development_team: Registries Team
    developers:
      - Shashi.Sharma
      - Parthasarathy.Hd
      - Kiran.Shivalingaiah
      - RAJESHKANNAN.BALU
      - Kundanam.Sreenivas
      - Lakshmi.A2
      - MohanaSundaram.A
      - Bhavya.Neelgar
      - Aravind.Thonupunuri
      - Gopika.Jayakumar
    enterprise_architect:
      - Maria.Brinas-Dobrowski
  compliance_designations:
    - None
  api_type: TENANT
  lifecycle_status: BUILD
  production_date: null
  retirement_date: null
  api_framework: Micronaut
  overall_data_classification: PUBLIC
  business_criticality: P2
  service_now_ci: CI02875146
  workload_placements:
    - where: core
      platform: tap
      proxy_pattern: side-car
  notification_ids:
    - description: ShuttleIO
      id: 'null'
    - description: slack
      id: GQ10ZD7UZ
  slack_channel_id: GQ10ZD7UZ
  nuid_ad_groups: null
  risk_rating: MEDIUM
  last_pentest_date: null
  links:
    issue_tracker: https://git.target.com/Registry-Modernization/backpack-registry-search/issues
    api_wiki_page: null
    code_repository: https://git.target.com/Registry-Modernization/backpack-registry-search
    ci_pipeline: https://git.target.com/Registry-Modernization/backpack-registry-search
    documentation_links:
      - https://git.target.com/Registry-Modernization/backpack-registry-search/blob/master/README.md
    logging_link:
      - http://platform.logging.target.com/goto/b6dc02a192efa17b59c15e539143ecaf
    metrics_link:
      - https://visualize.target.com/d/KXWja4RMk/target-platform-metrics-backpackregistry?orgId=1
    monitoring_link:
      - https://www.thalamus.target.com
    support_team_contact: TargetIndia-TTS-GRWS-Dev@Target.com
    api_spec: https://git.target.com/Registry-Modernization/backpack-registry/blob/master/api-spec/registries_search-v1.yml
  endpoints:
    external:
      production: https://api.target.com/registries_search/v1
      stage: https://stage-api.target.com/registries_search/v1
      qa: null
      ci: null
    internal:
      production: https://api-internal.target.com/registries_search/v1
      stage: https://stgapi-internal.target.com/registries_search/v1
      qa: null
      ci: null
securityDefinitions:
  openid_2.0_connect_stage:
    type: oauth2
    authorizationUrl: https://oauth.iam.perf.target.com/openid/connect/v1/userinfo
    flow: implicit
    scopes: {}
  openid_2.0_connect_prod:
    type: oauth2
    authorizationUrl: https://oauth.iam.target.com/openid/connect/v1/userinfo
    flow: implicit
    scopes: {}
paths:
  '/':
    x-data_classification: PUBLIC
    get:
      x-incident_priority: P2
      x-response_time_sla: 200ms
      x-success_http_code: '200'
      x-expected_tps: '100'
      summary: Search registries by guest first and last names
      description: Search registries by guest first and last names
      tags:
        - registries_search
      parameters:
        - name: first_name
          in: query
          description: Guest first name
          required: true
          type: string
        - name: last_name
          in: query
          description: Guest last name
          required: true
          type: string
        - name: key
          in: query
          description: The consumer's valid API key.
          required: true
          type: string
        - name: channel
          in: query
          description: The channel creating this request
          required: true
          type: string
        - name: sub_channel
          in: query
          description: The sub channel creating this request
          required: true
          type: string
        - name: location_id
          in: query
          description: The store id
          required: true
          type: integer
          format: int32
        - name: sort_field
          in: query
          description: sort field by given enum options
          required: false
          type: "string"
          enum: [ "NAME", "EVENT_DATE","LOCATION"]
        - name: sort_order
          in: query
          description: sort order by given enum options
          required: false
          type: "string"
          enum: [ "ASC", "DESC"]

      responses:
        '200':
          description: list of searched registires transfer objects
          schema:
            $ref: '#/definitions/RegistrySearchResponseTO'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error400'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error401'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error403'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error404'


definitions:
  RegistrySearchResponseTO:
    type: object
    properties:
      total_records:
        type: integer
        format: int32
      page_size:
        type: integer
        format: int32
      current_page:
        type: integer
        format: int32
      sort_field:
        type: string
      sort_type:
        type: string
      registries:
        $ref: '#/definitions/RegistrySearchDetailsTO'
  RegistrySearchDetailsTO:
    type: object
    properties:
      registry_id:
        type: string
      registry_status:
        type: string
      registry_title:
        type: string
      registrant_first_name:
        type: string
      registrant_last_name:
        type: string
      coregistrant_first_name:
        type: string
      coregistrant_last_name:
        type: string
      eventy_type:
        type: string
      event_date:
        type: string
      event_city:
        type: string
      event_state:
        type: string
      event_country:
        type: string
      image_info:
        $ref: '#/definitions/ImageInfoTO'
  ImageInfoTO:
    type: object
    properties:
      image_url:
        type: string
        description: Image URL
      image_id:
        type: string
        description: Image Identification number
      dimension:
        type: string
        description: Dimension of the specific image
      type:
        type: string
        description: Type of the specific item
      image_status:
        type: string
        description: Image Status


  Error401:
    type: object
    properties:
      message:
        type: string
        description: Authentication credentials were missing or incorrect
        example: Unauthorized
  Error400:
    type: object
    properties:
      message:
        type: string
        description: Invalid Request
        example: Bad Request
  Error403:
    type: object
    properties:
      message:
        type: string
        description: Forbidden Request
        example: Bad Request
  Error404:
    type: object
    properties:
      message:
        type: string
        description: URL requested is invalid or the resource requested does not exist
        example: Not Found
