# service level datacenter specific placeholders
elastic-env:
  primary: https://dbaasprod-el-ebackpack-prod-1617645940172.prod.target.com
  backup: https://dbaasprod-el-cbackpack-prod-1617645984804.prod.target.com
