micronaut:
  application:
    name: backpack-elasticsearch-app
  server:
    host: ${backpack-elasticsearch-app-host:localhost}
    port: 8081
    idle-timeout: 2000ms
    netty:
      max-header-size: 16384 # Handling RequestTooLarge headers - Default value (8192)

  metrics:
    binders:
      web:
        enabled: false # we are using our own binder via our custom micronaut-metrics lib

filter:
  server:
    order:
      mdc-filter: 50
      lists-brave-tracing-server-filter: 100
      list-authorization-filter: 200
      registry-channel-subchannel-filter: 400
  client:
    order:
      lists-brave-tracing-client-filter: 900
      metrics-filter: 850
      resilience-client-filter: 800
      oauth-filter: 701
      oauth-key-filter: 700
