micronaut:
  application:
    name: backpack-elasticsearch-app
  server:
    host: ${backpack-elasticsearch-app-host:localhost}
    port: 8081
    idle-timeout: 2000ms

  metrics:
    binders:
      web:
        enabled: false # we are using our own binder via our custom micronaut-metrics lib

lists:
  metrics:
    binders:
      http:
        enabled: true # we are using our own binder via our custom micronaut-metrics lib

jackson:
  property-naming-strategy: "SNAKE_CASE"

filter:
  server:
    order:
      mdc-filter: 50
      lists-brave-tracing-server-filter: 100
      list-authorization-filter: 200
      sanitizing-filter: 300
  client:
    order:
      lists-brave-tracing-client-filter: 900
      resilience-client-filter: 800
      oauth-filter: 701
      oauth-key-filter: 700

logging:
  mdc:
    enabled: true
    keys:
      - profile_id
      - x-api-id
    filter:
      path: /lists/**

resilience4j:
  circuitbreaker:
    failure-rate-threshold: 50                      # failure rate threshold in percentage (default: 50)
    wait-duration-secs-in-open-state: 1             # time cb waits before transitioning from open to half-open (default: 60s)
    sliding-window-type: TIME_BASED                 # possible values TIME_BASED or COUNT_BASED (default: COUNT_BASED)
    sliding-window-size: 5                          # seconds for TIME_BASED, request-count for COUNT_BASED (default: 100)
    minimum-number-of-calls: 2                      # min calls required (per sliding window period) before cb calculates error rate (default: 10)
    permitted-number-of-calls-in-half-open-state: 1 # Number of permitted calls when the CircuitBreaker is half open.

backends:
  primary:
    circuit-breaker:
      enabled: true
      failure-rate-threshold: 50            # failure rate threshold in percentage
      wait-duration-secs-in-open-state: 1   # time cb waits before transitioning from open to half-open
      sliding-window-type: TIME_BASED       # possible values TIME_BASED or COUNT_BASED
      sliding-window-size: 5                # seconds for TIME_BASED, request-count for COUNT_BASED
      minimum-number-of-calls: 2            # min calls required (per sliding window period) before cb calculates error rate.
  backup:
    circuit-breaker:
      enabled: true
      failure-rate-threshold: 50            # failure rate threshold in percentage
      wait-duration-secs-in-open-state: 1   # time cb waits before transitioning from open to half-open
      sliding-window-type: TIME_BASED       # possible values TIME_BASED or COUNT_BASED
      sliding-window-size: 5                # seconds for TIME_BASED, request-count for COUNT_BASED
      minimum-number-of-calls: 2            # min calls required (per sliding window period) before cb calculates error rate.

tracing:
  zipkin:
    enabled: false
    excluded-paths: /health
    b3-propagation-suppress: true
    sample-rate-percent: 0.5
    http:
      url: "https://zipkinserver.dev.target.com"
      messageMaxBytes: 50000
    app:
      name: backpackelasticsearch
      env: dev
      region: tdc

components:
  server:
    list-authorization-filter:
      base-uri: /backpackelasticsearch

msgbus:
  source: backpackelasticsearch
  dlq-source: backpackelasticsearch-dlq
  kafka:
    consumer:
      enabled: false
    producer:
      enabled: true
    dlqconsumer:
      enabled: false
    dlqproducer:
      enabled: true
    topic: lists-msg-bus
    consumer-group: backpack-elasticsearch-msg-bus-consumer
    consumer-batch-size: 10
    dlq-topic: lists-dlq
    dlq-consumer-group: backpack-elasticsearch-dlq-consumer
    dlq-event-retry-interval-secs: 1
    dlq-max-event-retry-count: 2
    dlq-consumer-batch-size: 10

