filters:
  - Cors
  - KeyValidation
  - ProxyHeaders
  - Auth
#upstream:
# TAP doesn't need upstream section
# TAP uses the protocol (HTTP/HTTPS) and port for the health check as the upstream for proxy.
# host: localhost
# port: 8080
# ssl: false
listenAddressPort: ":8080"
cors:
  whitelist:
    - https://editor.swagger.io
  allowCredentials: true
  allowHeaders:
    - Authorization
keyValidation:
  environment: "STAGE"
apiName: "backpack-elasticsearch"
metrics:
  enabled: true
auth:
  passOnNoAuth: true
  passOnNoAuthRoutes:
    GET:
      - "/health"
  clientTimeout: 30
  cacheExpireSeconds: 3600
  strategies:
    #    - strategy: ID2
    #      configuration:
    #        host: oauth.iam.perf.target.com
    #        port: 443
    #        ssl: true
    #        enterpriseValidator:
    #          host: gsp.perf.target.com
    #          port: 443
    #          ssl: true
    #        issuer:
    #          - 'https://oauth.iam.perf.target.com'
    - strategy: GSP
      configuration:
        host: gsp.perf.target.com
        port: 443
        path: gsp/oauth_validations/v3
        publicKeyEndpoint:
          host: gsp.perf.target.com
          port: 443
          path: gsp/oauth_tokens/v2/keys/
        ssl: true
        issuer:
          - "mi6"
        routesByScope:
          ecom.high:
            - GET: /:*
            - POST: /:*
            - PUT: /:*
            - DELETE: /:*
          ecom.low:
            - GET: /:*
            - POST: /:*
            - PUT: /:*
            - DELETE: /:*
          ecom.med:
            - GET: /:*
            - POST: /:*
            - PUT: /:*
            - DELETE: /:*
          ecom.none:
            - GET: /:*
            - POST: /:*
            - PUT: /:*
            - DELETE: /:*
        routesByASL:
          H:
            - GET: /:*
            - POST: /:*
            - PUT: /:*
            - DELETE: /:*
          L:
            - GET: /:*
            - POST: /:*
            - PUT: /:*
            - DELETE: /:*
          M:
            - GET: /:*
            - POST: /:*
            - PUT: /:*
            - DELETE: /:*
