version: 2
server:
  listen_address: localhost:8080
environment: stage
health:
  proxy:
   enabled: true
   path: /proxyhealth
api_name: backpack_elasticsearch-v1
metrics:
  push: true
handlers:
  key_validation:
    environment: STAGE
  cors:
    whitelist:
      - https://editor.swagger.io
    allow_any_target_domain: true
    allow_credentials: true
    allow_any_origin: true
    allowed_headers:
      - Authorization
